AWSTemplateFormatVersion: 2010-09-09
Description: >-
  cf-macro-slic-watch
Transform:
- AWS::Serverless-2016-10-31
Resources:
  CfMacroSlicWatch:
   Type: AWS::CloudFormation::Macro
   Properties:
     Name: CfMacroSlicWatch
     FunctionName: !GetAtt MacroLambdaFunction.Arn
     
  MacroLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName : cf-macro-slic-watch-function
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Lambda function that implements macro
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SNSTopic: !Ref MonitoringTopic
          
  MonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ssTopic2