AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-test-project

Transform:
  - AWS::Serverless-2016-10-31
  - SlicWatch-v2

Metadata:
  slicWatch:
    enabled: true
    # topicArn: ${env:ALARM_TOPIC}
    topicArn: !Ref MonitoringTopic
    alarms:
      Lambda:
        Invocations:
          enabled: true
          Threshold: 10
      SQS:
        AgeOfOldestMessage:
          Statistic: Maximum
          enabled: true
          Threshold: 60
        InFlightMessagesPc:
          Statistic: Maximum
          Threshold: 1 # 1% = 1200 for regular queues or 180 for FIFO queues

Resources:
  MonitoringTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: SS-Alarm-Topic2

  hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x
    Metadata:
      slicWatch:
        alarms:
          Lambda:
            Invocations:
              Threshold: 2

  ping:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x
    Metadata:
      slicWatch:
        dashboard:
          enabled: false

  throttler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x
      ReservedConcurrentExecutions: 0

  driveStream:
    Type: AWS::Serverless::Function
    Properties:
      Handler: stream-test-handler.handleDrive
      Runtime: nodejs16.x

  driveQueue:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x

  driveTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x

  streamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: basic-handler.hello
      Runtime: nodejs16.x
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt stream.Arn
            MaximumRetryAttempts: 0
            StartingPosition: LATEST

  stream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
 
