name: Publish SLIC Watch SAR application
on:
  push:
    branches:
      - slic-watch-sam-support
env:
  SAR_BUCKET_NAME : ${{ secrets.SAR_BUCKET_NAME }}
  AWS_REGION : "eu-west-1"
permissions:
  id-token: write
  contents: read
jobs:
  publish-sar:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.SAR_DEPLOYMENT_IAM_ROLE }}
          role-session-name: github-action-sar-deploy-session
          aws-region: ${{ env.AWS_REGION }}
      - name: Git clone the repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v2
      - name:
        run: |
          aws sts get-caller-identity
          npm ci
          sam build --base-dir . --template-file cf-macro/template.yaml
          sam package --output-template-file packaged.yaml --s3-bucket ${SAR_BUCKET_NAME}
          sam publish --template packaged.yaml --region ${AWS_REGION} --semantic-version $(cat package.json | jq -r '.version')
